version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://Kuzuryuz:1234@coworkingspace.nr0wkau.mongodb.net/?retryWrites=true&w=majority&appName=CoworkingSpace
      - JWT_SECRET=asdfjkl;;lkjfdsa
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=Ey7nTKnggBc0bRN8WUjyShw2qzOZ6KW4fUyqcKBePxY=
      - MONGO_URI=mongodb+srv://Kuzuryuz:1234@coworkingspace.nr0wkau.mongodb.net/?retryWrites=true&w=majority&appName=CoworkingSpace
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5000